@subdominio = sub-dominio-render

##############################
# Requests SIN base de datos #
##############################

###
# 1: Mostrar su código IDAT y su nombre en el siguiente formato: CÓDIGO - NOMBRE
###
GET http://localhost:5432/idat/nombre-completo

###
# 2: Mostrar su código IDAT
GET https://.onrender.com/idat/codigo

###
# 3: Mostrar su nombre completo
GET https://.onrender.com/idat/nombre-completo


##############################################
#         Requests CON base de datos         #
##############################################
# Tabla: cursos:                             #
#   - id: int (strategy=GenerationType.AUTO) #
#   - nombre: string                         #
#   - creditos: int                          #
##############################################


###
# 4: Listar cursos
GET https://.onrender.com/idat/curso/listar HTTP/1.1

###
# 5: Nuevo Curso
POST https://.onrender.com/idat/curso/nuevo HTTP/1.1
Content-Type: application/x-www-form-urlencoded

curso=jueves
&credits=5

###
# 6: Eliminar Curso
# el id lo acepta de parametro y devulve un not content
DELETE https://.onrender.com/idat/curso/eliminar/id HTTP/1.1
Content-Type: application/x-www-form-urlencoded

